In [1]:
import cv2

In [2]:
img = cv2.imread("galaxy.jpg",0) # 0 = greyscale , 1 = BGR

In [3]:
print(type(img))
print(img.shape) # dimensions of img
print(img)

<class 'numpy.ndarray'>
(1485, 990)
[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]


In [4]:
# Display img for sometime... then destroy it
cv2.imshow("image",img)
cv2.waitKey(0) # if 0 then waits for infinity
cv2.destroyAllWindows

<function destroyAllWindows>

In [5]:
# Resizing image
resize_img = cv2.resize(img,(445,742)) 
cv2.imshow("image",resize_img)
cv2.imwrite("galaxy_resized.jpg",resize_img) # Creates another image
cv2.waitKey(0) # if 0 then waits for infinity
cv2.destroyAllWindows

<function destroyAllWindows>